#!/usr/bin/env bash

setopt no_nomatch
DISABLE_UPDATE_PROMPT=true
DISABLE_AUTO_UPDATE=true
ZSH_DISABLE_COMPFIX=true
HOMEBREW_NO_ANALYTICS=1
ISABLE_MAGIC_FUNCTIONS=true
ZSH_THEME="ys"
HISTSIZE=100000
SAVEHIST=100000
